version: '3.8'

services:
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/bookcatalog
    depends_on:
      - db

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    ports:
      - "8081:5000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/inventorymanagement
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookcatalog
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:# Your Solution
